---
title: "obpg"
output: github_document
---

Access OPeNDAP OBPG data from R. Extract point or bounded boxes (as raster).

## Requirements

+ [R v4.1+](https://www.r-project.org/)

Packages from CRAN.

+ [rlang](https://CRAN.R-project.org/package=rlang)
+ [dplyr](https://CRAN.R-project.org/package=httr)
+ [sf](https://CRAN.R-project.org/package=sf)
+ [stars](https://CRAN.R-project.org/package=stars)
+ [tidyr](https://CRAN.R-project.org/package=tidyr)
+ [ncdf4](https://CRAN.R-project.org/package=ncdf4)

Packages from Github

+ [xyzt](https://github.com/BigelowLab/xyzt)


## Installation

```
remotes::install_github("BigelowLab/obpg")
```


### Usage
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(sf)
  library(obpg)
  library(xyzt)
  library(stars)
})
```


#### Working with points.  

See the [xyzt](https://github.com/BigelowLab/xyzt) package for more details on the example Gulf of Maine data.

```{r}
# read in example GOM points
x <- xyzt::read_gom() |>
  dplyr::select(-time, -depth) |>
  xyzt::as_POINT()

# generate a MUR url for a given date
url <- obpg_url("2020-07-12")

# open the resource
X <- ncdf4::nc_open(url)

# extract the data 
covars <- obpg::extract(x, X, varname = obpg::obpg_vars(X))

# bind to the input
(y <- dplyr::bind_cols(x, covars))
```


```{r}
# cleanup
ncdf4::nc_close(X)
```
